services:
  mariadb:
    image: mariadb
    command: --log-bin=fosho_binlog --binlog-format=ROW
    ports:
      - "3306:3306"
    volumes:
      - ./data/maria:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: fosho
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.15.1
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    restart: unless-stopped

  kibana:
     image: docker.elastic.co/kibana/kibana:8.13.4
     ports:
       - "5601:5601"
     environment:
       - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
     restart: unless-stopped

